syntax

diff --git a/.github/workflows/internal-pr-bundle-integration-test-cpp.yml b/.github/workflows/internal-pr-bundle-integration-test-cpp.yml
--- a/.github/workflows/internal-pr-bundle-integration-test-cpp.yml
+++ b/.github/workflows/internal-pr-bundle-integration-test-cpp.yml
@@ -21,44 +21,45 @@ jobs:
       fail-fast: false
       matrix:
         language: [ 'cpp' ]
+    
     steps:
     - name: Checkout repository
       uses: actions/checkout@4
 
-      - name: Install QLT
-        id: install-qlt
-        uses: ./.github/actions/install-qlt-local
-        with:
-          qlt-version: 'latest'
-          add-to-path: true
+    - name: Install QLT
+      id: install-qlt
+      uses: ./.github/actions/install-qlt-local
+      with:
+        qlt-version: 'latest'
+        add-to-path: true
 
-      - name: Validate QLT Installation
-        shell: bash
-        run: |
-          echo -e "Checking QLT Version:"
-          echo "QLT Home: ${{ steps.install-qlt.outputs.qlt-home }}"
-          qlt version
+    - name: Validate QLT Installation
+      shell: bash
+      run: |
+        echo -e "Checking QLT Version:"
+        echo "QLT Home: ${{ steps.install-qlt.outputs.qlt-home }}"
+        qlt version
 
-      - name: Create Bundle (compiled)
-        shell: bash
-        run: |
-          if ! qlt codeql run install --base example/ --custom-bundle  ; then
-            echo "Failed to generate bundle."
-            exit 1
-          fi
+    - name: Create Bundle (compiled)
+      shell: bash
+      run: |
+        if ! qlt codeql run install --base example/ --custom-bundle  ; then
+          echo "Failed to generate bundle."
+          exit 1
+        fi
 
-          # ensure bundle runs 
+        # ensure bundle runs 
 
-          if ! qlt query run install-packs --use-bundle --base example/  ; then
-            echo "Failed to install query packs with tool."
-            exit 1
-          fi
+        if ! qlt query run install-packs --use-bundle --base example/  ; then
+          echo "Failed to install query packs with tool."
+          exit 1
+        fi
 
-      - name: Validate Bundle Existence
-        shell: bash
-        run: |
-          echo "Checking Bundle Existence"
-          ls -l ${{ env.QLT_CODEQL_HOME }}/../out/
+    - name: Validate Bundle Existence
+      shell: bash
+      run: |
+        echo "Checking Bundle Existence"
+        ls -l ${{ env.QLT_CODEQL_HOME }}/../out/
 
     - name: Initialize CodeQL
       uses: github/codeql-action/init@v2
