check actual command

diff --git a/.github/workflows/internal-validate-workflow-files.yml b/.github/workflows/internal-validate-workflow-files.yml
--- a/.github/workflows/internal-validate-workflow-files.yml
+++ b/.github/workflows/internal-validate-workflow-files.yml
@@ -34,12 +34,18 @@ jobs:
       - name: Generate Workflow Files (Test Feature)
         shell: bash
         run: |
-          qlt test init --use-runner ubuntu-latest --num-threads 4 --language cpp --automation-type actions --development --overwrite-existing
+          if ! qlt test init --use-runner ubuntu-latest --num-threads 4 --language cpp --automation-type actions --development --overwrite-existing ; then
+            echo "Failed to generate test workflow files."
+            exit 1
+          fi
 
       - name: Generate Workflow Files (Validation Feature)
         shell: bash
         run: |
-          qlt validation init --use-runner ubuntu-latest --language cpp --automation-type actions --development --overwrite-existing
+          if ! qlt validation init --use-runner ubuntu-latest --language cpp --automation-type actions --development --overwrite-existing ; then
+            echo "Failed to generate validation workflow files."
+            exit 1
+          fi
 
       - name: Check Git Clean Status 
         shell: bash
